steps:
  # 1. Install dependencies using a clean environment
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']

  # 2. Execute the production build script
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      # Inject the API_KEY from the build-time environment variables
      - 'API_KEY=$_API_KEY'

# Define where to store the resulting sharded artifacts
artifacts:
  objects:
    location: 'gs://$PROJECT_ID-build-artifacts/shards/$BUILD_ID'
    paths: ['dist/**']

# Performance settings for high-fidelity industrial builds
timeout: '1200s'
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
