
export interface User {
  name: string;
  email: string;
  esin: string; // EnvirosAgro Social Identification Number
  mnemonic: string; // 12-word recovery phrase
  regDate: string;
  avatar?: string;
  role: string;
  location: string;
  countryCode?: string;
  lineNumber?: string;
  isPhoneVerified?: boolean;
  wallet: EACWallet;
  metrics: SustainabilityMetrics;
  skills: Record<string, number>; // Maps category (e.g., 'Hydroponics') to points
  isReadyForHire: boolean;
  zodiacFlower?: {
    month: string;
    flower: string;
    color: string;
    pointsAdded: boolean;
  };
}

export interface EACWallet {
  balance: number;
  bonusBalance: number; // Non-withdrawable registration incentives
  tier: 'Seed' | 'Sprout' | 'Harvest';
  lifetimeEarned: number; // Used for "Reputation Score"
}

export interface SustainabilityMetrics {
  agriculturalCodeU: number; 
  timeConstantTau: number;  
  sustainabilityScore: number;
  socialImmunity: number; // 0-100: Resistance to SID
  viralLoadSID: number;   // 0-100: Presence of Social Influenza
}

export interface ResearchPaper {
  id: string;
  title: string;
  author: string;
  authorEsin: string;
  abstract: string;
  content: string;
  thrust: string;
  status: 'Draft' | 'Peer-Review' | 'Registered' | 'Invention';
  impactScore: number; // 0-100
  rating: number; // 1-5
  eacRewards: number;
  timestamp: string;
  iotDataUsed?: boolean;
  externalDataHashes?: string[];
}

export interface WorkerProfile {
  id: string;
  name: string;
  skills: string[];
  sustainabilityRating: number;
  verifiedHours: number;
  isOpenToWork: boolean;
  lifetimeEAC: number;
}

export interface AgroProject {
  id: string;
  name: string;
  adminEsin: string;
  collectiveId?: string; // Optional: Project led by a social collective
  description: string;
  thrust: 'Societal' | 'Environmental' | 'Human' | 'Technological' | 'Industry';
  status: 'Ideation' | 'Verification' | 'Funding' | 'Execution' | 'Closure';
  totalCapital: number;
  fundedAmount: number;
  batchesClaimed: number;
  totalBatches: number;
  progress: number; // 0-100
  roiEstimate: number; // Percentage
  collateralLocked: number;
  profitsAccrued: number; // Total EAC profits generated by project
  investorShareRatio: number; // Percentage (e.g. 0.15 for 15%)
  performanceIndex: number; // 0-100 based on collective feedback
  memberCount: number; // Number of collective members backing the project
}

export interface AgroBlock {
  hash: string;
  prevHash: string;
  timestamp: string;
  transactions: AgroTransaction[];
  validator: string;
  status: 'Confirmed' | 'Pending' | 'Mining';
}

export interface AgroTransaction {
  id: string;
  type: 'Harvest' | 'Audit' | 'Transfer' | 'CarbonMint' | 'ReactionMining' | 'MarketTrade' | 'EvidenceUpload' | 'Reward' | 'Burn' | 'Recycle' | 'Dividend';
  farmId: string;
  details: string;
  value: number;
  unit: string;
}

export type ViewState = 'dashboard' | 'wallet' | 'sustainability' | 'economy' | 'industrial' | 'intelligence' | 'community' | 'explorer' | 'ecosystem' | 'media' | 'info' | 'profile' | 'investor' | 'vendor' | 'ingest' | 'tools' | 'channelling' | 'circular' | 'crm' | 'tqm' | 'research';
