import React from 'react';
import { ViewState } from '../types';

const ResearchInnovation = React.lazy(() => import('./ResearchInnovation'));
const MeshProtocol = React.lazy(() => import('./MeshProtocol'));
const Agrowild = React.lazy(() => import('./Agrowild'));
const ContractFarming = React.lazy(() => import('./ContractFarming'));
const TQMGrid = React.lazy(() => import('./TQMGrid'));
const LiveFarming = React.lazy(() => import('./LiveFarming'));
const CircularGrid = React.lazy(() => import('./CircularGrid'));
const Dashboard = React.lazy(() => import('./Dashboard'));
const Sustainability = React.lazy(() => import('./Sustainability'));
const Economy = React.lazy(() => import('./Economy'));
const Industrial = React.lazy(() => import('./Industrial'));
const Intelligence = React.lazy(() => import('./Intelligence'));
const Community = React.lazy(() => import('./Community'));
const Explorer = React.lazy(() => import('./Explorer'));
const Ecosystem = React.lazy(() => import('./Ecosystem'));
const MediaHub = React.lazy(() => import('./MediaHub'));
const InfoPortal = React.lazy(() => import('./InfoPortal'));
const Login = React.lazy(() => import('./Login'));
const AgroWallet = React.lazy(() => import('./AgroWallet'));
const UserProfile = React.lazy(() => import('./UserProfile'));
const InvestorPortal = React.lazy(() => import('./InvestorPortal'));
const VendorPortal = React.lazy(() => import('./VendorPortal'));
const NetworkIngest = React.lazy(() => import('./NetworkIngest'));
const HardwareRegistry = React.lazy(() => import('./HardwareRegistry'));
const DeviceControl = React.lazy(() => import('./DeviceControl'));
const ToolsSection = React.lazy(() => import('./ToolsSection'));
const LiveVoiceBridge = React.lazy(() => import('./LiveVoiceBridge'));
const Channelling = React.lazy(() => import('./Channelling'));
const Governance = React.lazy(() => import('./GlobalGovernance').then(m => ({ default: m.GlobalGovernance })));
const AIOracleView = React.lazy(() => import('./AIOracleView'));
const CarbonCredits = React.lazy(() => import('./CarbonCredits'));
const Traceability = React.lazy(() => import('./Traceability'));
const Marketplace = React.lazy(() => import('./Marketplace'));
const NexusCRM = React.lazy(() => import('./NexusCRM'));
const AgroMultimediaGenerator = React.lazy(() => import('./AgroMultimediaGenerator'));
const CostAccountingDashboard = React.lazy(() => import('./CostAccountingDashboard'));
const InternalControlDashboard = React.lazy(() => import('./InternalControlDashboard'));
const ImpactDashboard = React.lazy(() => import('./ImpactDashboard'));
const TraceabilityMap = React.lazy(() => import('./TraceabilityMap'));
const TelemetryHub = React.lazy(() => import('./TelemetryHub'));
const SwarmOrchestrator = React.lazy(() => import('./SwarmOrchestrator'));
const AssetVerification = React.lazy(() => import('./AssetVerification'));
const MRVEngine = React.lazy(() => import('./MRVEngine'));
const ReputationDashboard = React.lazy(() => import('./ReputationDashboard'));
const SettingsPortal = React.lazy(() => import('./SettingsPortal'));
const EscrowPortal = React.lazy(() => import('./EscrowPortal'));
const TemporalVideo = React.lazy(() => import('./TemporalVideo'));
const Agrobot = React.lazy(() => import('./Agrobot'));
const AgrobotSync = React.lazy(() => import('./AgrobotSync'));
const AgroRegency = React.lazy(() => import('./AgroRegency'));
const CodeOfLaws = React.lazy(() => import('./CodeOfLaws'));
const AgroCalendar = React.lazy(() => import('./AgroCalendar'));
const ChromaSystem = React.lazy(() => import('./ChromaSystem'));
const EnvirosAgroStore = React.lazy(() => import('./EnvirosAgroStore'));
const AgroValueEnhancement = React.lazy(() => import('./AgroValueEnhancement'));
const DigitalMRV = React.lazy(() => import('./DigitalMRV'));
const OnlineGarden = React.lazy(() => import('./OnlineGarden'));
const FarmOS = React.lazy(() => import('./FarmOS'));
const MediaLedger = React.lazy(() => import('./MediaLedger'));
const Sitemap = React.lazy(() => import('./Sitemap'));
const AgroLangAnalyst = React.lazy(() => import('./AgroLangAnalyst'));
const AIAnalyst = React.lazy(() => import('./AIAnalyst'));
const EducationalResources = React.lazy(() => import('./EducationalResources'));
const RegistryHandshake = React.lazy(() => import('./RegistryHandshake'));
const NaturalResources = React.lazy(() => import('./NaturalResources'));
const IntranetPortal = React.lazy(() => import('./IntranetPortal'));
const CEA = React.lazy(() => import('./CEA'));
const Biotechnology = React.lazy(() => import('./Biotechnology'));
const Permaculture = React.lazy(() => import('./Permaculture'));
const EmergencyPortal = React.lazy(() => import('./EmergencyPortal'));
const Impact = React.lazy(() => import('./Impact'));

export const getComponentForView = (
  view: ViewState,
  props: any
): React.ReactNode => {
  switch (view) {
    case 'dashboard': return <Dashboard {...props} />;
    case 'sustainability': return <Sustainability {...props} />;
    case 'economy': return <Economy {...props} />;
    case 'industrial': return <Industrial {...props} />;
    case 'intelligence': return <Intelligence {...props} />;
    case 'community': return <Community {...props} />;
    case 'explorer': return <Explorer {...props} />;
    case 'ecosystem': return <Ecosystem {...props} />;
    case 'media': return <MediaHub {...props} />;
    case 'info': return <InfoPortal {...props} />;
    case 'auth': return <Login {...props} />;
    case 'wallet': return <AgroWallet {...props} />;
    case 'profile': return <UserProfile {...props} />;
    case 'investor': return <InvestorPortal {...props} />;
    case 'vendor': return <VendorPortal {...props} />;
    case 'ingest': return <NetworkIngest {...props} />;
    case 'hardware_registry': return <HardwareRegistry {...props} />;
    case 'device_control': return <DeviceControl {...props} />;
    case 'tools': return <ToolsSection {...props} />;
    case 'live_voice_bridge': return <LiveVoiceBridge {...props} />;
    case 'channelling': return <Channelling {...props} />;
    case 'governance': return <Governance {...props} />;
    case 'ai_oracle': return <AIOracleView {...props} />;
    case 'carbon_credits': return <CarbonCredits {...props} />;
    case 'traceability': return <Traceability {...props} />;
    case 'marketplace': return <Marketplace {...props} />;
    case 'crm': return <NexusCRM {...props} />;
    case 'multimedia_generator': return <AgroMultimediaGenerator {...props} />;
    case 'cost_accounting': return <CostAccountingDashboard {...props} />;
    case 'internal_control': return <InternalControlDashboard {...props} />;
    case 'impact_dashboard': return <ImpactDashboard {...props} />;
    case 'traceability_map': return <TraceabilityMap {...props} />;
    case 'telemetry_hub': return <TelemetryHub {...props} />;
    case 'swarm_orchestrator': return <SwarmOrchestrator {...props} />;
    case 'asset_verification': return <AssetVerification {...props} />;
    case 'agrowild': return <Agrowild {...props} />;
    case 'mesh_protocol': return <MeshProtocol {...props} />;
    case 'contract_farming': return <ContractFarming {...props} />;
    case 'tqm': return <TQMGrid {...props} />;
    case 'live_farming': return <LiveFarming {...props} />;
    case 'circular': return <CircularGrid {...props} />;
    case 'research': return <ResearchInnovation {...props} />;
    case 'mrv_engine': return <MRVEngine {...props} />;
    case 'reputation_dashboard': return <ReputationDashboard {...props} />;
    case 'escrow_portal': return <EscrowPortal {...props} />;
    case 'settings': return <SettingsPortal {...props} />;
    case 'temporal_video': return <TemporalVideo {...props} />;
    case 'agro_regency': return <AgroRegency {...props} />;
    case 'code_of_laws': return <CodeOfLaws {...props} />;
    case 'agro_calendar': return <AgroCalendar {...props} />;
    case 'chroma_system': return <ChromaSystem {...props} />;
    case 'envirosagro_store': return <EnvirosAgroStore {...props} />;
    case 'agro_value_enhancement': return <AgroValueEnhancement {...props} />;
    case 'digital_mrv': return <DigitalMRV {...props} />;
    case 'online_garden': return <OnlineGarden {...props} />;
    case 'farm_os': return <FarmOS {...props} />;
    case 'media_ledger': return <MediaLedger {...props} />;
    case 'sitemap': return <Sitemap {...props} />;
    case 'agro_lang_analyst': return <AgroLangAnalyst {...props} />;
    case 'ai_analyst': return <AIAnalyst {...props} />;
    case 'educational_resources': return <EducationalResources {...props} />;
    case 'registry_handshake': return <RegistryHandshake {...props} />;
    case 'impact': return <Impact {...props} />;
    case 'animal_world': return <NaturalResources {...props} type="animal_world" />;
    case 'plants_world': return <NaturalResources {...props} type="plants_world" />;
    case 'aqua_portal': return <NaturalResources {...props} type="aqua_portal" />;
    case 'soil_portal': return <NaturalResources {...props} type="soil_portal" />;
    case 'air_portal': return <NaturalResources {...props} type="air_portal" />;
    case 'intranet': return <IntranetPortal {...props} />;
    case 'cea_portal': return <CEA {...props} />;
    case 'biotech_hub': return <Biotechnology {...props} />;
    case 'permaculture_hub': return <Permaculture {...props} />;
    case 'emergency_portal': return <EmergencyPortal {...props} />;
    case 'agrobot': return (
      <React.Suspense fallback={props.loadingFallback || <div>Loading...</div>}>
         {props.viewSection === 'sync' ? <AgrobotSync {...props} /> : <Agrobot {...props} />}
      </React.Suspense>
    );

    default: return <Dashboard {...props} />;
  }
};
